### ISSUE TITLE
Some errors in the PDF?

### ISSUE THREAD

**Issue by linchpinlin** [HazyResearch/evaporate#1]
[technical-report.pdf](https://github.com/HazyResearch/evaporate/blob/main/technical-report.pdf)
Page 6:
The tables generated by Evaporate-Code **are are** on average 13.8 pair F1 points worse than those produced using **Evaporate-Code**.
The tables generated by Evaporate-Code are on average 13.8 pair F1 points worse than those produced using **Evaporate-Direct**.

**Comment by simran-arora** [comment]
Fixed in the arxiv and will update this in the pdf, thanks!
