### ISSUE TITLE
[QUESTION] GPT-J-6b

### ISSUE THREAD

**Issue by albertus-andito** [HazyResearch/evaporate#12]
Hi,

Thanks for open-sourcing this code. Interesting stuffs!

Have you tried running EVAPORATE-CODE+ with open source huggingface models, such as GPT-J-6b? 
What's the overall performance? Is it comparable to text-davinci-003?

**Comment by simran-arora** [comment]
Hi! In preliminary analysis we find the quality with GPT-J-6B to fall short on function generation and thus quality to be worse than text-davinci-003. We are looking at various options and thinking about how to acquire good open-source LMs for that step. If you have pointers as well, let us know!

**Comment by albertus-andito** [comment]
I'm wondering whether the newly released StarChat can be used for the function generation step...
