### ISSUE TITLE
when i run bash run.sh, i got a issue"Failed to apply prompt". What should I do?

### ISSUE THREAD

**Issue by jy-101361-1810897** [HazyResearch/evaporate#14]

**Comment by simran-arora** [comment]
Hi! Thanks for trying the code. Can you include some information from the error message backtrace?

**Comment by jy-101361-1810897** [comment]
Thanks.I got 'Failed to apply prompt' like this.
Data lake
Chunking files: 100%|███████████████████████| 100/100 [00:00<00:00, 1230.00it/s]
Data-lake: fda_510ks, Train size: 10
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K161714.txt: 8
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K172913.txt: 11
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K190219.txt: 15
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K171641.txt: 10
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K163260.txt: 23
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K151923.txt: 7
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K181288.txt: 9
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K173927.txt: 9
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K162705.txt: 4
Chunks in sample file ./data/evaporate/fda-ai-pmas/510k/K180886.txt: 5
Directly extracting metadata from chunks:   0%|          | 0/10 [00:00<?, ?it/s]Failed to apply prompt to chunk.
Failed to apply prompt to chunk.
Failed to apply prompt to chunk.

I find it in line 55 in schema_identification.py. I debug to find why it got the issue. For example, I enter apply_prompt function and the next function. And I cannot find the cause of the problem.

**Comment by delabbb** [comment]
May I ask you how you solve this problem?I'm facing the same situation.
