### ISSUE TITLE
If I want to use other LM to run, like ChatGLM, where should I modify？

### ISSUE THREAD

**Issue by jy-101361-1810897** [HazyResearch/evaporate#15]

**Comment by simran-arora** [comment]
Hi! You can modify this to specify your model: https://github.com/HazyResearch/evaporate/blob/83204a54dd97fb0f51a01643b4fc16c97fc5e472/evaporate/run_profiler.py#L456 

All the prompts are applied (via API or local models) and cached through the functions in this file: https://github.com/HazyResearch/evaporate/blob/main/evaporate/utils.py

If you are using manifest for your model, you would not need to make any modifications. If you need to add a function for a new model interface, you can modify this function.
https://github.com/HazyResearch/evaporate/blob/83204a54dd97fb0f51a01643b4fc16c97fc5e472/evaporate/utils.py#L11

Please let me know if you have additional questions!
