### ISSUE TITLE
ModuleNotFoundError: No module named 'manifest'

### ISSUE THREAD

**Issue by raywgs** [HazyResearch/evaporate#16]
Hi, 

I'm getting ModuleNotFoundError: No module named 'manifest'. Do I clone the manifest folder inside the metal-evap folder or the evaporate subfolder or the evaporate parent folder? 

Thanks

**Comment by simran-arora** [comment]
Hi! Using the setup instructions, you should have pip installed manifest-ml
https://github.com/HazyResearch/evaporate/blob/main/setup.py

Let me know if that works!

**Comment by simran-arora** [comment]
If you want to clone it, then you can do it anywhere!

Within the clone folder of manifest, you can use one terminal to load the model and obtain a connection URL to the model as specified in the manifest README (think of this like a URL to an OpenAI API, but instead it points to a local model). Then in a separate terminal, you would run the evaporate code. So it doesn't matter where you clone manifest!

**Comment by raywgs** [comment]
Thanks for the response. I installed manifest-ml via pip, now I run into this error: `AttributeError: 'ClientConnectionPool' object has no attribute 'get_client'`

**Comment by raywgs** [comment]
yea, seems like it should be get_current_client instead

**Comment by simran-arora** [comment]
Yes, that's correct. I think the API may have changed!

For reference v1.0.2 of Manifest was available when this code was released.
