### ISSUE TITLE
if I want to replace another dataset, where need to be changed?

### ISSUE THREAD

**Issue by jy-101361-1810897** [HazyResearch/evaporate#17]

**Comment by simran-arora** [comment]
Hi! You will need to:

1. Add your data filepaths here as we did for FDA: https://github.com/HazyResearch/evaporate/blob/83204a54dd97fb0f51a01643b4fc16c97fc5e472/evaporate/configs.py#L58
2. Specify how to load your files as we did here for FDA: https://github.com/HazyResearch/evaporate/blob/83204a54dd97fb0f51a01643b4fc16c97fc5e472/evaporate/run_profiler.py#L22
