### ISSUE TITLE
weak supervision error 

### ISSUE THREAD

**Issue by raywgs** [HazyResearch/evaporate#19]
Hey, 

I got this error: 
<img width="997" alt="CleanShot 2023-06-12 at 11 46 25@2x" src="https://github.com/HazyResearch/evaporate/assets/128401657/071ba5bd-d4c7-403e-a648-005b5021edd6">

Is there any fix for this? 

Thanks

**Comment by simran-arora** [comment]
Hi, it seems like Average unique votes per document is `nan` 
I haven't seen any issue with the weak supervision code -- can you provide more information about what the label model training set looks like (number of labeling functions, examples of the vote vectors, etc.) if you haven't found a fix as yet? Thanks!

**Comment by raywgs** [comment]
I'm running it on the swde dataset.

**Comment by raywgs** [comment]
it might be the gold extractions file path; should the file paths of the individual files inside the gold extractions json match exactly the file path of the dataset.

**Comment by simran-arora** [comment]
Did this fix your issue?
