### ISSUE TITLE
missing gold attribute file

### ISSUE THREAD

**Issue by theblackcat102** [HazyResearch/evaporate#9]
I am having trouble running the basic run.sh (fda 510k) mainly I am missing the `ground_truth/fda_510ks_gold_extractions.json` file, do you know where it's located?

I can't seem to find in the evaporate dataset

**Comment by seyuboglu** [comment]
The ground truth table is located in this JSON file https://huggingface.co/datasets/hazyresearch/evaporate/blob/main/data/fda_510ks/table.json
